# Assets
ticker0: "CL=F"   # (Micro) WTI crude oil (cash)
ticker1: "RB=F"   # RBOB (full contract ticker, mini margins).

# Start Date: note the Micros started on `2021-07-12`.
start_date: "2016-01-01"

# Strategy Parameters
z_entry: 2.8  # 3.2  # 2.0  # 1.78
z_exit: 1.71  # 1.0  # 1.71
use_fixed_train_size: True

# Minimum price fluctuation = 100 barrels.
# Contract unit = $0.01 per barrel
# Effective minimum tick per contract = 0.01 ($/barrel) * 100 (barrels) = $1
#multiplier0: 1.0
#multiplier1: 0.42  # https://www.cmegroup.com/markets/energy/refined-products/micro-rbob-gasoline.contractSpecs.html
multiplier0: 100
multiplier1: 4200

margin0: 500   # https://www.cmegroup.com/markets/energy/crude-oil/micro-wti-crude-oil.margins.html
margin1: 770   # https://www.cmegroup.com/markets/energy/refined-products/micro-rbob-gasoline.margins.html

# Futures-like commission: x --> x%.
commission0: 2.0
commission1: 2.0

# MCL Specs:
#  Trading terminates 1 business day before the corresponding CL contract month
#  or 4 business days before the 25th calendar of the month prior to the contract month.
#  If the 25th calendar day is not a business day, trading terminates 5 business days
#  before the 25th calendar day of the month prior to the contract month.
# NOTE (JP): THERE ARE 6 TRADING DAYS PER WEEK - SATURDAY MUST ALSO BE A `BUSINESS DAY` IN THIS CONTEXT.
expiry0: 25
expiry1: "b_month_end"  # RBOB Specs: trading terminates on the last business day of the month prior to the contract month.