defaults:
  - _self_
  - data: daily  # [hourly, daily]
  - pairs: micro_wti_oil_micro_rbob
#  - micro_wti_oil
#  - micro_rbob
#  - pairs: wti_crude_oil_rbob
#  - pairs: test_oil_gas_idealised
#  - pairs: micro_wti_crude_oil_mini_natural_gas
#  - pairs: sp500_fut_russell2000_fut

broker:
  # Starting cash balance
  cash_initial: 1000000.0
#  cash_initial: 100000.0
#  cash_initial: 5000.0

strategy:
#  dt: 1.0  # 1/23
  dt: 1.0/252
  A: 1.0
  allow_single_legs: True  # Allow non-delta-neutral positions, e.g. in 1 asset only.

risk_free_rate: 0.0   # 0.01  # 0.0x == x%.
risk_per_trade: 0.02  # 0.0x == x%, maximum risk percentage per trade.

# TODO
convert_timezone: False

# TODO: dynamic lookup.
config_dir: "/Users/joe/code/trading/algo/strategies/mean_reversion/configs/"
