defaults:
  - _self_
  - data: daily  # [hourly, daily]
  - pairs: micro_wti_oil_micro_rbob
#  - pairs: wti_crude_oil_rbob
#  - pairs: test_oil_gas_idealised

broker:
  # Starting cash balance
  cash_initial: 5000000.0

strategy:
  dt: 1.0/252  # 1.0
  A: 1.0
  allow_single_legs: True  # Allow non-delta-neutral positions, e.g. in 1 asset only.
  require_cointegrated: False
  trade_integer_quantities: True  # True e.g. for futures contracts, False e.g. for fractional shares and indices.
  roll_at_expiry: True

# 0.0x == x%, maximum risk percentage per trade.
risk_per_trade: 0.05

# Sharpe: 0.0x == x%.
risk_free_rate: 0.0

# TODO
convert_timezone: False

config_dir: "/Users/joe/code/trading/algo/strategies/mean_reversion/configs/"
