defaults:
  - _self_
  - data: hourly  # [hourly, daily]
  - pairs: micro_wti_crude_oil_mini_natural_gas
#  - pairs: chevron_exxon

broker:
  cash_initial: 100000.0  # Starting cash balance
#  cash_initial: 1000.0  # Starting cash balance
#  cash_initial: 100.0  # Starting cash balance

strategy:
  dt: 1.0  # 1/23
  A: 1.0
