defaults:
  - _self_
  - data: hourly  # [hourly, daily]
#  - pairs: test_oil_oil
  - pairs: test_oil_gas_idealised
#  - pairs: micro_wti_crude_oil_mini_natural_gas

broker:
#  cash_initial: 100000.0  # Starting cash balance
  cash_initial: 5000.0  # Starting cash balance
#  cash_initial: 100.0  # Starting cash balance

strategy:
  dt: 1.0  # 1/23
  A: 1.0
  allow_single_legs: True  # Allo non-delta-neutral positions, e.g. in 1 asset only.

risk_free_rate: 0.0   # 0.01  # 0.0x == x%.
risk_per_trade: 0.02  # 0.0x == x%, maximum risk percentage per trade.